import { Injectable, NestInterceptor, ExecutionContext, CallHandler } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { Observable } from 'rxjs';
import { tap } from 'rxjs/operators';
import { EventBusService } from '../event-bus/event-bus.service.js';
import { EMITS_EVENT_KEY } from '../decorators/emits.decorator.js';
import { BaseEvent } from '../event-bus/base.event.js';

/**
 * Internal wrapper for automatic events generated by the @Emits decorator.
 */
class AutoEvent extends BaseEvent<any> { }

/**
 * Interceptor that listens for the @Emits decorator and sends the method's result to the EventBus.
 */
@Injectable()
export class EventEmitInterceptor implements NestInterceptor {
    constructor(
        private readonly _reflector: Reflector,
        private readonly _eventBus: EventBusService,
    ) { }

    /**
     * Captures the return value and emits it via EventBusService.
     */
    intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
        const eventName = this._reflector.get<string>(EMITS_EVENT_KEY, context.getHandler());

        return next.handle().pipe(
            tap(async (data) => {
                if (eventName) {
                    const eventPayload = data instanceof BaseEvent ? data : new AutoEvent(data);
                    await this._eventBus.emit(eventName, eventPayload);
                }
            }),
        );
    }
}
