import { applyDecorators } from '@nestjs/common';
import { LogMethod } from './log-method.decorator.js';
import { EDAContext } from '../event-bus/eda-context.holder.js';
import { BaseEvent } from '../event-bus/base.event.js';
import { preserveMetadata } from '../utils/decorator.util.js';

/**
 * Internal wrapper for automatic events generated by the @Emits decorator.
 */
class AutoEvent extends BaseEvent<any> { }

/**
 * Decorator that automatically emits the return value of a method as a system event.
 * Works as a method wrapper, ensuring compatibility even when called outside of NestJS lifecycle (e.g. by Discord handlers).
 *
 * @param eventName - The name of the event to emit.
 *
 * @example
 * @Emits('user.created')
 * async createUser(dto: any) { ... }
 */
export function Emits(eventName: string): MethodDecorator {
    return (target: any, propertyKey: string | symbol, descriptor: PropertyDescriptor) => {
        const originalMethod = descriptor.value;
        descriptor.value = async function (...args: any[]) {
            const result = await originalMethod.apply(this, args);

            if (result !== undefined && eventName) {
                try {
                    const eventBus = EDAContext.getEventBus();
                    const eventPayload = result instanceof BaseEvent ? result : new AutoEvent(result);
                    await eventBus.emit(eventName, eventPayload);
                } catch (error) {
                    console.error(`[@Emits] Failed to emit event ${eventName}:`, error);
                }
            }

            return result;
        };
        preserveMetadata(originalMethod, descriptor.value);
        return applyDecorators(LogMethod({ description: `Event Emission: ${eventName}` }))(target, propertyKey, descriptor);
    };
}
