export const ICLIENT_TOKEN = Symbol('ICLIENT_TOKEN');
export const DISCORD_CLIENT_OPTIONS = Symbol('DISCORD_CLIENT_OPTIONS');
export const ICOMMAND_HANDLER_TOKEN = Symbol('ICOMMAND_HANDLER_TOKEN');
export const IBUTTON_HANDLER_TOKEN = Symbol('IBUTTON_HANDLER_TOKEN');
export const ISELECT_MENU_HANDLER_TOKEN = Symbol('ISELECT_MENU_HANDLER_TOKEN');
export const IMODAL_HANDLER_TOKEN = Symbol('IMODAL_HANDLER_TOKEN');
export const IINTERACTIONS_MANAGER_TOKEN = Symbol('IINTERACTIONS_MANAGER_TOKEN');
export const IDISCORD_EVENT_MANAGER_TOKEN = Symbol('IDISCORD_EVENT_MANAGER_TOKEN');
